import{Save}from'./save.js';
import{DIFFICULTY,MODES}from'./config.js';
import{app,toast,modal,closeModal,bindHeader}from'./ui.js';
export class GameBase{
 constructor(mode,home){this.mode=mode;this.home=home;this.state=null;this.tab='overview';this.autosave=null}
 start(state){this.state=state;this.render();this.autosave=setInterval(()=>this.save(false),15000)}
 stop(){clearInterval(this.autosave)}
 save(show=true){const saved=Save.save(this.mode,this.state);if(show)toast(saved?'保存しました':'保存できませんでした。ブラウザの空き容量を確認してください',saved?'good':'bad');return saved}
 difficulty(){return DIFFICULTY[this.state.difficulty]}
 shell(content,tabs=''){if(this.state?.ending){const e=this.state.ending;return`${this.header()}<main class="content"><section class="panel" style="max-width:760px;margin:36px auto"><p class="eyebrow">THE END</p><h1>${e.title}</h1><p style="font-size:1.08rem;line-height:1.9">${e.text}</p><div class="notice" style="margin-top:18px">${e.summary}</div><div class="modal-actions" style="margin-top:20px"><button class="btn primary" id="ending-home">WORLDIAへ戻る</button></div></section></main>`}return`${this.header()}<main class="content">${content}</main>${tabs}`}
 header(){const m=MODES[this.mode];return`<header class="topbar"><button class="icon-btn" id="back-home">←</button><div><div class="brand">${m.name}</div><div class="tiny muted">${this.state.turn}${m.unit}目・${this.state.difficulty}</div></div><div class="spacer"></div><button class="btn" id="manual-save">保存</button><button class="icon-btn" id="game-settings">⋯</button></header>`}
 bind(){bindHeader({back:()=>{this.save(false);this.stop();this.home()},save:()=>this.save(),settings:()=>this.settings()});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{this.tab=b.dataset.tab;this.render()});document.querySelector('#ending-home')?.addEventListener('click',()=>{this.save(false);this.stop();this.home()})}
 settings(){modal(`<h2>ゲームデータ</h2><p class="muted">このモードだけに適用されます。</p><div class="modal-actions"><button class="btn" id="close-settings">閉じる</button><button class="btn danger" id="delete-save">データ削除</button></div>`);document.querySelector('#close-settings').onclick=closeModal;document.querySelector('#delete-save').onclick=()=>{if(confirm('このモードのセーブデータを削除しますか？')){Save.remove(this.mode);closeModal();this.stop();this.home()}}}
 spend(amount){if(this.state.cash!==undefined){if(this.state.cash<amount){toast('資金が足りません','bad');return false}this.state.cash-=amount}else if(this.state.funds!==undefined){if(this.state.funds<amount){toast('市の資金が足りません','bad');return false}this.state.funds-=amount}else if(this.state.budget!==undefined){if(this.state.budget<amount){toast('国家予算が足りません','bad');return false}this.state.budget-=amount}return true}
 checkEnding(){const s=this.state;if(!s||s.ending)return false;if(this.mode==='city'&&s.turn>=37){let title='任期満了。町は残りました。';let text='36か月の市政が終了しました。道路を引き、家を建て、税率を悩み抜いた結果、市長の任期だけは予定どおり終わりました。';if(s.population<=10){title='市長はいる。市民がいない。';text='都市計画は完成しましたが、肝心の住民がほぼいなくなりました。広々としていて渋滞だけはありません。'}else if(s.population>=300&&s.satisfaction>=75){title='住みたい街ランキング1位。住めない街にも1位。';text='理想の街は完成しました。人気が出すぎて地価まで上昇し、昔からの住民から「もう家賃が高い」と言われました。'}else if(s.funds<0){title='立派な街、立派な赤字。';text='公共サービスも建物も残りました。残らなかったのは市の貯金でした。次の市長への引き継ぎ資料だけが分厚くなりました。'}else if(s.satisfaction<40){title='都市は完成。市民アンケートは未完成。';text='建物は増えましたが、市民の満足度は最後まで追いつきませんでした。市役所は「長期的には成果が出る」と発表しています。'}s.ending={title,text,summary:`最終人口 ${Math.round(s.population)}人・満足度 ${Math.round(s.satisfaction)}・市の資金 ¥${Math.round(s.funds).toLocaleString()}`};s.logs?.push('36か月の任期が満了しました');return true}
 if(this.mode==='country'&&s.turn>=13){const before=Number(s.budget)||0,deficit=Math.max(5,Math.round((Math.abs(before)*.12+8)*10)/10),settlement=Math.round((before+deficit)*10)/10;s.budget=-deficit;s.logs?.push(`任期末の国債償還・社会保障精算 ${settlement.toFixed(1)}Bで最終赤字 ${deficit.toFixed(1)}B`);let text='12年間の国家経営が終了しました。黒字化の気配が見えた瞬間、国債償還・社会保障・インフラ更新の請求書が同じ日に届きました。国家経営は、どうやっても最後に赤字でした。';if(s.satisfaction>=75&&s.credit>=70)text='国民も市場もかなり満足しています。そこで任期末の国債償還・社会保障・インフラ更新を全部精算したところ、やっぱり赤字でした。支持率では払えませんでした。';else if(s.satisfaction<35)text='財政だけでなく国民の機嫌まで赤字気味です。最後の精算をすると国家予算も正式に赤字になり、次の政権へ「健闘を祈る」とだけ書いた引き継ぎ書が残りました。';s.ending={title:'国家経営、最終決算は赤字。',text,summary:`GDP ${Number(s.gdp).toFixed(1)}B・満足度 ${Math.round(s.satisfaction)}・最終予算 -${deficit.toFixed(1)}B`};return true}
 if(this.mode==='shop'&&s.turn>=31){if(s.kind==='cafe'){const before=Number(s.cash)||0,deficit=Math.max(30000,Math.round(Math.abs(before)*.12+50000)),settlement=Math.round(before+deficit);s.cash=-deficit;s.profit=-settlement;s.logs?.push(`月末精算・設備更新・原材料調整費 ${settlement.toLocaleString()}円`);let text='30日間、豆の原価、家賃、人件費と戦いました。最後にエスプレッソマシンの更新費と月末精算が同時に来て、どう経営しても赤字で閉店です。コーヒーだけは最後まで黒かったです。';if(s.reputation>=75)text='評判は最高、常連も増えました。ところが設備更新と月末精算をしたら赤字でした。「人気店」と「儲かる店」は別物だったようです。コーヒーだけは黒字っぽい色でした。';s.ending={title:'カフェ、繁盛。そして赤字。',text,summary:`30日目・評判 ${Math.round(s.reputation)}・最終残高 -¥${deficit.toLocaleString()}`};return true}let title='30日営業、おつかれさまでした。',text='ひと月の営業が終了しました。売上表と在庫表を閉じて、店長はようやく椅子に座れました。';if(s.cash>=700000){title='店は大成功。店長は疲労困憊。';text='ひと月でしっかり利益を残しました。次の課題は売上ではなく、店長がちゃんと休むことです。'}else if(s.cash<100000){title='営業終了。財布もほぼ終了。';text='店は30日間もちました。残った資金を数えた結果、次の仕入れより先に電卓の電池を買うか悩むことになりました。'}s.ending={title,text,summary:`所持金 ¥${Math.round(s.cash).toLocaleString()}・評判 ${Math.round(s.reputation)}・フォロワー ${Math.round(s.followers)}`};return true}
 if(this.mode==='festival'&&s.eventsHeld>=5){let title='5公演完走。撤収までがフェスです。',text='5つのイベントを開催し、会社としてひと区切りを迎えました。最後の出演者が帰ったあと、運営チームに残った最大の仕事はケーブルを巻くことでした。';if(s.companyRep>=75){title='伝説の主催者になりました。翌朝は普通に撤収です。';text='評判もSNSも大成功。観客には伝説の夜として残りましたが、主催者には翌朝のゴミ分別と機材返却が残りました。'}else if(s.cash<0){title='アンコールはありません。請求書はあります。';text='5公演を走り切りました。歓声が止んだあとも、会場費と運営費の請求だけはしっかり残りました。'}s.ending={title,text,summary:`開催 ${s.eventsHeld}回・会社評判 ${Math.round(s.companyRep)}・会社資金 ¥${Math.round(s.cash).toLocaleString()}`};return true}return false}
 commit(){this.checkEnding();this.save(false);this.render()}
}
