import{MODES,escapeHTML}from'./config.js';
import{Save}from'./save.js';
import{app,modal,closeModal,toast}from'./ui.js';
import{ShopGame,createShopState}from'../games/shop/shop.js';
import{FestivalGame,createFestivalState}from'../games/festival/festival.js';
import{CityGame,createCityState}from'../games/city/city.js';
import{CountryGame,createCountryState}from'../games/country/country.js';
import{SHOP_TYPES}from'../games/shop/data.js';
const constructors={shop:[ShopGame,createShopState],festival:[FestivalGame,createFestivalState],city:[CityGame,createCityState],country:[CountryGame,createCountryState]};
let activeGame=null;
function home(){activeGame?.stop();activeGame=null;const cards=Object.entries(MODES).map(([id,m],index)=>{const sum=Save.summary(id);return`<button type="button" class="mode-card" data-mode="${id}" style="--accent:${m.accent}"><span class="mode-number">0${index+1}</span><div class="mode-icon">${m.icon}</div><h2>${m.name}</h2><p>${{shop:'価格と人員を整え、地域に根づく店を育てる。',festival:'出演者と会場を組み、当日の熱気をつくる。',city:'限られた土地と予算から、暮らしを設計する。',country:'政策・産業・外交を動かし、国の先を決める。'}[id]}</p><div class="mode-status">${sum?`<span class="chip">${sum.turn}${m.unit}目から</span><span class="chip">${sum.difficulty}</span>`:'<span class="chip">はじめから</span>'}</div></button>`}).join('');app().innerHTML=`<header class="topbar"><div class="brand">W<em>O</em>RLDIA</div><div class="spacer"></div><button class="btn" id="install-app" hidden>アプリを追加</button></header><main class="content"><section class="hero"><p class="eyebrow">4つの運営シミュレーション</p><h1>判断の積み重ねが、<br><span>世界を変える。</span></h1><p>店、音楽イベント、都市、国家。短い操作で状況を読み、次の一手を決めていくシミュレーションゲームです。</p></section><section class="mode-grid">${cards}</section><p class="tiny muted" style="text-align:center;margin-top:24px">自動保存 / オフライン対応</p></main>`;document.querySelectorAll('[data-mode]').forEach(card=>card.onclick=()=>choose(card.dataset.mode));bindInstall()}
function choose(mode){const state=Save.load(mode);if(state)return launch(mode,state);newGame(mode)}
function newGame(mode){let difficulty='NORMAL',kind='cafe';modal(`<p class="eyebrow">新しく始める</p><h2>${MODES[mode].name}</h2><div class="field"><label>難易度</label><div class="difficulty-grid">${['EASY','NORMAL','HARD'].map(d=>`<button class="difficulty ${d===difficulty?'selected':''}" data-difficulty="${d}"><b>${d}</b><br><span class="tiny muted">${{EASY:'気軽に成長',NORMAL:'標準',HARD:'厳しい運営'}[d]}</span></button>`).join('')}</div></div>${mode==='shop'?`<div class="field"><label>お店の種類</label><select id="shop-kind">${Object.entries(SHOP_TYPES).map(([id,x])=>`<option value="${id}">${x.name}</option>`).join('')}</select></div>`:''}<div class="modal-actions"><button class="btn" id="cancel-new">戻る</button><button class="btn primary" id="create-new">ゲーム開始</button></div>`,{closeable:false});document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{difficulty=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(x=>x.classList.toggle('selected',x===b))});document.querySelector('#shop-kind')?.addEventListener('change',e=>kind=e.target.value);document.querySelector('#cancel-new').onclick=closeModal;document.querySelector('#create-new').onclick=()=>{const create=constructors[mode][1],state=mode==='shop'?create(difficulty,kind):create(difficulty);Save.save(mode,state);closeModal();launch(mode,state,true)}}
function launch(mode,state,isNew=false){const Game=constructors[mode][0];activeGame=new Game(home);activeGame.start(state);if(isNew)startTutorial(mode)}
function startTutorial(mode){const meta=Save.meta();if(meta.tutorials?.[mode])return;modal(`<p class="eyebrow">操作ガイド</p><h2>最初の一歩</h2><p>画面上部に大切な数字、中央に操作、右側または下側に状況のヒントが表示されます。</p><ol class="muted"><li>下のタブで管理画面を切り替える</li><li>設定を調整して時間を進める</li><li>結果を確認して次の判断をする</li></ol><p>まずは実際にタブを押して、それぞれの管理画面を見てみましょう。</p><div class="modal-actions"><button class="btn primary" id="tutorial-start">タブを押して始める</button></div>`,{closeable:false});document.querySelector('#tutorial-start').onclick=()=>{meta.tutorials={...(meta.tutorials||{}),[mode]:true};Save.setMeta(meta);closeModal();document.querySelectorAll('.tab').forEach(x=>x.animate([{transform:'translateY(0)'},{transform:'translateY(-4px)'},{transform:'translateY(0)'}],{duration:500,iterations:2}));toast('変更は15秒ごとに自動保存されます')}}
let installPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;const b=document.querySelector('#install-app');if(b)b.hidden=false});function bindInstall(){const b=document.querySelector('#install-app');if(installPrompt&&b){b.hidden=false;b.onclick=async()=>{await installPrompt.prompt();installPrompt=null;b.hidden=true}}}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
window.addEventListener('beforeunload',()=>activeGame?.save(false));
home();
