import{GameBase}from'../../js/game-base.js';
import{app,stat,meter,tabs,chart,toast,floatDelta}from'../../js/ui.js';
import{clamp,rnd,money}from'../../js/config.js';
import{trend}from'../../js/economy.js';
import{rollEvent,resolveEvent}from'../../js/events.js';
import{INDUSTRIES,NATIONS,POLICY_INFO}from'./data.js';
export function createCountryState(difficulty){return{version:1,difficulty,turn:1,name:'ルミナリア共和国',population:8.4,gdp:310,budget:Math.round(48*({EASY:1.35,NORMAL:1,HARD:.72}[difficulty])*10)/10,taxRevenue:0,satisfaction:58,education:55,health:57,safety:63,technology:46,environment:61,energy:68,food:74,unemployment:6.8,inflation:2.1,credit:57,stability:60,incomeTax:18,corporateTax:22,policy:{education:8,healthcare:8,science:5,infrastructure:6,environment:4,energyPolicy:5,industry:5},industries:structuredClone(INDUSTRIES),nations:structuredClone(NATIONS),history:[310],logs:['新政権が発足しました。'],pendingEvent:null};}
export class CountryGame extends GameBase{
 constructor(home){super('country',home)}
 render(){const s=this.state,content=`<div class="resource-strip">${stat('国家予算',s.budget,'num')}${stat('GDP',s.gdp,'num')}${stat('人口',s.population,'num')}${stat('満足度',s.satisfaction)}${stat('失業率',s.unemployment,'pct')}${stat('国際信用',s.credit)}</div><div class="game-layout"><section>${this.view()}</section><aside class="panel"><h3>国家指標</h3>${meter('教育',s.education)}${meter('医療',s.health)}${meter('技術',s.technology)}${meter('環境',s.environment)}${meter('エネルギー',s.energy)}${meter('食料',s.food)}${s.pendingEvent?this.eventView():`<div class="notice">${this.advice()}</div>`}</aside></div>`;app().innerHTML=this.shell(content,tabs([['overview','概要'],['policy','政策'],['industry','産業'],['diplomacy','外交']],this.tab));this.bind();this.bindCountry()}
 view(){const s=this.state;if(this.tab==='policy')return`<div class="section-title"><h2>政策と予算配分</h2><button class="btn primary" id="next-year">翌年へ →</button></div><section class="panel"><div class="control-row"><label>所得税</label><b class="control-value">${s.incomeTax}%</b><input data-tax="incomeTax" type="range" min="5" max="40" value="${s.incomeTax}"></div><div class="control-row"><label>法人税</label><b class="control-value">${s.corporateTax}%</b><input data-tax="corporateTax" type="range" min="5" max="40" value="${s.corporateTax}"></div><p class="muted">税率が高いほど税収は増えますが、満足度や産業成長が鈍ります。</p></section><div class="card-grid" style="margin-top:12px">${Object.entries(POLICY_INFO).map(([id,[name]])=>`<article class="item-card"><h4>${name}</h4><div class="control-row"><input data-policy="${id}" type="range" min="1" max="16" value="${s.policy[id]}"><b class="control-value">${s.policy[id]}B</b></div><p>${this.policyText(id)}</p></article>`).join('')}</div>`;
 if(this.tab==='industry')return`<div class="section-title"><h2>国内産業</h2><button class="btn primary" id="next-year">翌年へ →</button></div><div class="card-grid">${s.industries.map(i=>`<article class="item-card"><div class="row"><h4>${i.name}</h4><span class="chip" style="color:${i.growth>=0?'var(--mint)':'var(--red)'}">${i.growth>=0?'+':''}${i.growth.toFixed(1)}%</span></div>${meter('産業規模',i.value)}<div class="control-row"><input data-industry="${i.id}" type="range" min="0" max="15" value="${i.support}"><b class="control-value">${i.support}B</b></div></article>`).join('')}</div>`;
 if(this.tab==='diplomacy')return`<div class="section-title"><h2>外交</h2><button class="btn primary" id="next-year">翌年へ →</button></div><div class="card-grid">${s.nations.map(n=>`<article class="item-card"><div class="row"><h4>${n.name}</h4><span class="chip">関係 ${Math.round(n.relation)}</span></div>${meter('経済力',n.economy)}${meter('技術力',n.technology)}<p>貿易規模 ${n.trade}B ${n.agreement?'・経済協定あり':''}</p><div class="actions"><button class="btn" data-diplomacy="trade" data-nation="${n.id}">貿易拡大 1B</button><button class="btn" data-diplomacy="tech" data-nation="${n.id}">技術協力 2B</button><button class="btn" data-diplomacy="aid" data-nation="${n.id}">援助 1B</button><button class="btn" data-diplomacy="agreement" data-nation="${n.id}" ${n.agreement?'disabled':''}>経済協定 3B</button></div></article>`).join('')}</div>`;
 return`<div class="section-title"><div><p class="eyebrow">NATIONAL CABINET</p><h2>${s.name}</h2></div><button class="btn primary" id="next-year">翌年へ →</button></div><section class="panel"><h3>GDP推移（B）</h3>${chart(s.history)}<div class="resource-strip">${stat('税収',s.taxRevenue,'num')}${stat('インフレ',s.inflation,'pct')}${stat('治安',s.safety)}${stat('安定度',s.stability)}</div></section><div class="section-title"><h3>政策レポート</h3></div><section class="panel timeline">${s.logs.slice(-8).reverse().map((l,i)=>`<div class="log"><time>${s.turn-i}年</time><span>${l}</span></div>`).join('')}</section>`}
 policyText(id){return{education:'将来の生産性が上がるが効果は緩やか。',healthcare:'健康と満足度、労働力を支える。',science:'IT・製造業と技術力を伸ばす。',infrastructure:'産業全体と雇用を支える。',environment:'環境改善と一部産業の負担が発生。',energyPolicy:'供給安定と製造業を支える。',industry:'産業全体へ広く支援する。'}[id]}
 advice(){const s=this.state,total=Object.values(s.policy).reduce((a,b)=>a+b,0)+s.industries.reduce((a,b)=>a+b.support,0);if(total>s.budget+s.taxRevenue)return'計画支出が収入を超えています。赤字は信用とインフレに影響します。';if(s.unemployment>10)return'失業率が高い状態です。インフラ・産業支援・貿易が雇用を作ります。';if(s.inflation>6)return'インフレが高く、国民生活と満足度を圧迫しています。支出配分を見直しましょう。';return'経済は安定しています。短期の満足度と長期の技術投資の配分が重要です。'}
 eventView(){const e=this.state.pendingEvent;return`<article class="item-card event-card"><h4>${e.title}</h4><p>${e.text}</p>${e.options?e.options.map((o,i)=>`<button class="btn" data-event="${i}">${o.label}</button>`).join(''):'<button class="btn" data-dismiss-event>確認</button>'}</article>`}
 bindCountry(){document.querySelectorAll('#next-year').forEach(b=>b.onclick=()=>this.nextYear());document.querySelectorAll('[data-tax]').forEach(x=>x.oninput=()=>{this.state[x.dataset.tax]=+x.value;this.render()});document.querySelectorAll('[data-policy]').forEach(x=>x.oninput=()=>{this.state.policy[x.dataset.policy]=+x.value;this.render()});document.querySelectorAll('[data-industry]').forEach(x=>x.oninput=()=>{this.state.industries.find(i=>i.id===x.dataset.industry).support=+x.value;this.render()});document.querySelectorAll('[data-diplomacy]').forEach(b=>b.onclick=()=>this.diplomacy(b.dataset.diplomacy,b.dataset.nation));document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{resolveEvent(this.state,+b.dataset.event);this.commit()});document.querySelector('[data-dismiss-event]')?.addEventListener('click',()=>{this.state.pendingEvent=null;this.commit()})}
 diplomacy(action,id){const s=this.state,n=s.nations.find(x=>x.id===id),cost={trade:1,tech:2,aid:1,agreement:3}[action];if(!this.spend(cost))return;if(action==='trade'){n.trade+=2;n.relation=clamp(n.relation+3)}if(action==='tech'){s.technology=clamp(s.technology+1.5);n.relation=clamp(n.relation+5)}if(action==='aid'){s.credit=clamp(s.credit+2);n.relation=clamp(n.relation+7)}if(action==='agreement'){n.agreement=true;n.trade+=4;n.relation=clamp(n.relation+8)}this.commit()}
 nextYear(){const s=this.state,d=this.difficulty(),trade=s.nations.reduce((a,n)=>a+n.trade*(n.agreement?1.35:1),0),avgIndustry=s.industries.reduce((a,i)=>a+i.value,0)/s.industries.length,taxDrag=(s.incomeTax+s.corporateTax-35)*.08;let weightedGrowth=0;s.industries.forEach(i=>{let boost=i.support*.14+s.policy.industry*.06+s.policy.infrastructure*.035+trade*.018-taxDrag;if(i.id==='it')boost+=s.policy.science*.14+s.technology*.025;if(i.id==='manufacturing')boost+=s.energy*.018+s.policy.science*.06;if(i.id==='agriculture')boost+=s.environment*.012+s.food*.01;if(i.id==='tourism')boost+=s.environment*.025+s.credit*.014;if(i.id==='finance')boost+=s.credit*.018-s.inflation*.16;if(i.id==='energy')boost+=s.policy.energyPolicy*.16;i.growth=clamp(boost-2.2+rnd(-.8,.8),-8,12)*d.demand;i.value=clamp(i.value+i.growth*.18,5,100);weightedGrowth+=i.growth});const growth=weightedGrowth/s.industries.length;s.gdp=Math.max(20,Math.round(s.gdp*(1+growth/100)*10)/10);s.taxRevenue=Math.round(s.gdp*((s.incomeTax*.55+s.corporateTax*.45)/100)*.62*10)/10;const policyCost=Object.values(s.policy).reduce((a,b)=>a+b,0),industryCost=s.industries.reduce((a,i)=>a+i.support,0),net=s.taxRevenue-policyCost-industryCost;s.budget=Math.round((s.budget+net)*10)/10;s.education=clamp(s.education+(s.policy.education-6)*.45);s.health=clamp(s.health+(s.policy.healthcare-6)*.45);s.technology=clamp(s.technology+(s.policy.science-4)*.5);s.environment=clamp(s.environment+(s.policy.environment-4)*.65-s.industries.find(i=>i.id==='manufacturing').growth*.06);s.energy=clamp(s.energy+(s.policy.energyPolicy-5)*.5);s.food=clamp(55+s.industries.find(i=>i.id==='agriculture').value*.4);s.unemployment=clamp(s.unemployment-growth*.3-s.policy.infrastructure*.05+1.2,1,25);s.inflation=clamp(s.inflation+Math.max(0,-net)*.035+growth*.06-1,-2,15);s.stability=clamp((s.safety+s.credit+s.satisfaction)/3);const taxPain=(s.incomeTax-15)*.6,inflationPain=Math.max(0,s.inflation-2)*2;s.satisfaction=clamp(s.health*.18+s.education*.12+s.safety*.14+(100-s.unemployment*3)*.2+(100-inflationPain*3)*.13+s.environment*.1+35-taxPain);s.credit=clamp(s.credit+(net>=0?1.5:-Math.abs(net)*.08)+(growth>0?.6:-1));s.population=Math.round(s.population*(1+(s.health-50)*.0008+(s.satisfaction-50)*.0004)*100)/100;s.history=trend(s.history,s.gdp);s.turn++;rollEvent('country',s,d);s.logs.push(`GDP ${growth>=0?'+':''}${growth.toFixed(1)}%、財政 ${net>=0?'+':''}${net.toFixed(1)}B`);floatDelta(`GDP ${growth>=0?'+':''}${growth.toFixed(1)}%`,growth<0);this.commit()}
}
