import{GameBase}from'../../js/game-base.js';
import{app,stat,meter,tabs,chart,toast,floatDelta}from'../../js/ui.js';
import{clamp,money}from'../../js/config.js';
import{trend}from'../../js/economy.js';
import{rollEvent,resolveEvent}from'../../js/events.js';
import{BUILDINGS,CAT_CLASS}from'./data.js';
export function createCityState(difficulty){const map=Array(64).fill(null);map[27]='road';map[28]='road';map[35]='road';map[36]='road';map[18]='house';map[19]='house';map[26]='house';map[34]='house';map[29]='store';map[37]='store';return{version:1,difficulty,turn:1,funds:Math.round(3200000*({EASY:1.35,NORMAL:1,HARD:.72}[difficulty])),population:48,taxRate:10,taxIncome:0,expenses:0,jobs:36,externalJobs:0,unemployment:0,safety:55,education:48,health:52,environment:70,traffic:82,landValue:35,satisfaction:62,economy:50,map,selected:'house',history:[48],logs:['市長として小さな町の発展計画を開始しました。'],pendingEvent:null};}
export class CityGame extends GameBase{
 constructor(home){super('city',home);this.category='住宅'}
 render(){const s=this.state,content=`<div class="resource-strip">${stat('市の資金',s.funds,'money')}${stat('人口',s.population)}${stat('税収/月',s.taxIncome,'money')}${stat('失業率',s.unemployment,'pct')}${stat('満足度',s.satisfaction)}${stat('地価',s.landValue)}</div><div class="game-layout"><section>${this.view()}</section><aside class="panel"><h3>都市指標</h3>${meter('治安',s.safety)}${meter('教育',s.education)}${meter('医療',s.health)}${meter('環境',s.environment)}${meter('交通',s.traffic)}${s.pendingEvent?this.eventView():`<div class="notice">${this.advice()}</div>`}</aside></div>`;app().innerHTML=this.shell(content,tabs([['map','マップ'],['build','建設'],['policy','行政'],['data','統計']],this.tab));this.bind();this.bindCity()}
 counts(){return this.state.map.reduce((o,id)=>(id&&(o[id]=(o[id]||0)+1),o),{})}
 view(){const s=this.state;if(this.tab==='build')return`<div class="section-title"><h2>建設メニュー</h2><span class="chip">選択: ${BUILDINGS.find(b=>b.id===s.selected)?.name||'なし'}</span></div><div class="row wrap">${['住宅','商業','公共','インフラ'].map(c=>`<button class="btn ${c===this.category?'primary':''}" data-category="${c}">${c}</button>`).join('')}</div><div class="card-grid" style="margin-top:12px">${BUILDINGS.filter(b=>b.category===this.category).map(b=>`<article class="item-card"><div class="row"><span class="mode-icon">${b.icon}</span><div><h4>${b.name}</h4><p>${b.housing?`収容 ${b.housing}人`:b.jobs?`雇用 ${b.jobs}人`:'都市機能'}</p></div></div><button class="btn ${s.selected===b.id?'good':'primary'}" data-select-building="${b.id}">${money(Math.round(b.cost*this.difficulty().cost))}</button></article>`).join('')}</div>`;
 if(this.tab==='policy')return`<div class="section-title"><h2>市政運営</h2><button class="btn primary" id="next-month">翌月へ →</button></div><section class="panel"><div class="control-row"><label>住民税率</label><b class="control-value">${s.taxRate}%</b><input id="city-tax" type="range" min="3" max="25" value="${s.taxRate}"></div><p class="muted">税率を上げると税収が増えますが、人口流入と満足度が下がります。</p><div class="actions"><button class="btn" data-service="safety">治安対策 ¥180,000</button><button class="btn" data-service="education">教育支援 ¥220,000</button><button class="btn" data-service="health">医療支援 ¥240,000</button><button class="btn" data-service="environment">環境整備 ¥160,000</button></div></section>`;
 if(this.tab==='data')return`<div class="section-title"><h2>都市統計</h2><button class="btn primary" id="next-month">翌月へ →</button></div><section class="panel"><h3>人口推移</h3>${chart(s.history)}<div class="meter-pair">${meter('雇用充足',clamp(s.jobs/Math.max(1,s.population*.45)*100))}${meter('市民満足度',s.satisfaction)}</div></section><section class="panel timeline" style="margin-top:12px">${s.logs.slice(-8).reverse().map((l,i)=>`<div class="log"><time>${s.turn-i}月</time><span>${l}</span></div>`).join('')}</section>`;
 return`<div class="section-title"><div><p class="eyebrow">CITY GRID</p><h2>WORLDIA CITY</h2></div><button class="btn primary" id="next-month">翌月へ →</button></div>${this.mapView()}<p class="tiny muted">空きマスを押すと選択中の建物を建設。建物を長押しせずタップすると詳細を確認できます。</p>`}
 mapView(){return`<div class="city-map">${this.state.map.map((id,i)=>{const b=BUILDINGS.find(x=>x.id===id);return`<button class="tile ${b?CAT_CLASS[b.category]:''} ${id==='road'?'road':''}" data-tile="${i}" aria-label="${b?.name||'空き地'}">${b?`<span>${b.icon}</span>`:''}</button>`}).join('')}</div>`}
 advice(){const s=this.state,c=this.counts();if(!(c.power&&c.water))return'発電所と水道施設がないと、大きな人口増加は起きません。';if(s.unemployment>15)return'仕事が不足しています。商業施設やオフィスを増やしましょう。';if(s.traffic<45)return'交通が混雑しています。道路、駅、バス停を追加しましょう。';return'都市は安定しています。住宅と雇用を同時に増やすと成長が続きます。'}
 eventView(){const e=this.state.pendingEvent;return`<article class="item-card event-card"><h4>${e.title}</h4><p>${e.text}</p>${e.options?e.options.map((o,i)=>`<button class="btn" data-event="${i}">${o.label}</button>`).join(''):'<button class="btn" data-dismiss-event>確認</button>'}</article>`}
 bindCity(){document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{this.category=b.dataset.category;this.render()});document.querySelectorAll('[data-select-building]').forEach(b=>b.onclick=()=>{this.state.selected=b.dataset.selectBuilding;this.tab='map';this.render()});document.querySelectorAll('[data-tile]').forEach(t=>t.onclick=()=>this.place(+t.dataset.tile));document.querySelectorAll('#next-month').forEach(b=>b.onclick=()=>this.nextMonth());const tax=document.querySelector('#city-tax');if(tax){tax.oninput=e=>{this.state.taxRate=+e.target.value;e.target.parentElement.querySelector('.control-value').textContent=`${this.state.taxRate}%`;this.save(false)};tax.onchange=()=>this.render()}document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>this.service(b.dataset.service));document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{if(!resolveEvent(this.state,+b.dataset.event))return toast('この選択に必要な資金が足りません','bad');this.commit()});document.querySelector('[data-dismiss-event]')?.addEventListener('click',()=>{this.state.pendingEvent=null;this.commit()})}
 place(index){const s=this.state;if(s.map[index])return toast('建物があるマスです','bad');const b=BUILDINGS.find(x=>x.id===s.selected);if(!b)return;const cost=Math.round(b.cost*this.difficulty().cost);if(!this.spend(cost))return;s.map[index]=b.id;s.jobs+=b.jobs;floatDelta(`${b.name} 建設`);this.commit()}
 service(key){const info={safety:180000,education:220000,health:240000,environment:160000},cost=Math.round(info[key]*this.difficulty().cost);if(!this.spend(cost))return;this.state[key]=clamp(this.state[key]+9);this.commit()}
 nextMonth(){const s=this.state,c=this.counts(),housing=BUILDINGS.reduce((a,b)=>a+(c[b.id]||0)*b.housing,0),buildingJobs=BUILDINGS.reduce((a,b)=>a+(c[b.id]||0)*b.jobs,0),utilities=(c.power||0)>0&&(c.water||0)>0,jobs=buildingJobs*(utilities?1:.65)+(s.externalJobs||0),workforce=Math.max(1,s.population*.45),employed=Math.min(jobs,workforce),service=(s.safety+s.education+s.health+s.environment)/4,taxAppeal=clamp(115-s.taxRate*3),jobRatio=clamp(jobs/workforce*70),trafficLoad=(s.population+employed*1.5)/Math.max(1,(c.road||0)*110+(c.station||0)*1200+(c.bus||0)*120);s.traffic=clamp(90-trafficLoad*8);const capacityFactor=clamp((housing-s.population)/Math.max(1,housing)*100),growth=Math.round((capacityFactor*.22+service*.08+taxAppeal*.08+jobRatio*.06-18)*(utilities?1:.18)*this.difficulty().demand);s.population=Math.max(0,Math.min(housing,Math.round(s.population+growth)));const currentWorkforce=Math.max(1,s.population*.45),currentEmployed=Math.min(jobs,currentWorkforce);s.jobs=Math.round(jobs);s.unemployment=clamp((currentWorkforce-currentEmployed)/currentWorkforce*100);s.satisfaction=clamp(service*.48+s.traffic*.17+taxAppeal*.22+clamp(100-s.unemployment*3)*.13);s.landValue=clamp(s.landValue+(s.satisfaction-50)*.035+(c.park||0)*.08);s.taxIncome=Math.round(s.population*26000*(s.taxRate/100)+currentEmployed*9000*(s.taxRate/100));s.expenses=Math.round((Object.values(c).reduce((a,b)=>a+b,0)*11500+s.population*600)*this.difficulty().cost);const net=s.taxIncome-s.expenses;s.funds+=net;s.history=trend(s.history,s.population);s.turn++;rollEvent('city',s,this.difficulty());s.logs.push(`人口 ${growth>=0?'+':''}${growth}、収支 ${money(net)}`);floatDelta(`人口 ${growth>=0?'+':''}${growth}`,growth<0);this.commit()}
}
