import{GameBase}from'../../js/game-base.js';
import{app,stat,meter,tabs,chart,toast,floatDelta}from'../../js/ui.js';
import{clamp,rnd,pick,money,escapeHTML}from'../../js/config.js';
import{trend}from'../../js/economy.js';
import{rollEvent,resolveEvent}from'../../js/events.js';
import{VENUES,ARTISTS,WEATHER}from'./data.js';
export function createFestivalState(difficulty){return{version:1,difficulty,turn:1,cash:Math.round(2600000*({EASY:1.35,NORMAL:1,HARD:.72}[difficulty])),companyRep:45,followers:850,eventsHeld:0,history:[0],plan:{name:'WORLDIA BEAT',venue:'club',ticket:4800,artists:['8'],stages:1,staff:25,promotion:180000,sound:50,lighting:50,security:50,food:50,goods:40,weeks:3},live:null,lastResult:null,logs:['イベント会社を設立しました。'],pendingEvent:null};}
export class FestivalGame extends GameBase{
 constructor(home){super('festival',home);this.liveTimer=null}
 save(show=true){const running=this.state?.live?.running===true;if(running)this.state.live.running=false;const result=super.save(show);if(running)this.state.live.running=true;return result}
 stop(){clearInterval(this.liveTimer);if(this.state?.live){this.state.live.running=false;this.save(false)}super.stop()}
 render(){const s=this.state;const content=`<div class="resource-strip">${stat('会社資金',s.cash,'money')}${stat('会社評判',s.companyRep)}${stat('SNS',s.followers)}${stat('開催数',s.eventsHeld)}${stat('予定規模',this.venue().capacity)}${stat('準備期間',s.plan.weeks)}</div><div class="game-layout"><section>${this.view()}</section><aside class="panel"><h3>企画バランス</h3>${meter('宣伝',Math.min(100,s.plan.promotion/7000))}${meter('音響',s.plan.sound)}${meter('照明',s.plan.lighting)}${meter('警備',s.plan.security)}<div class="notice">${this.advice()}</div>${s.pendingEvent?this.eventView():''}</aside></div>`;app().innerHTML=this.shell(content,tabs([['plan','企画'],['artists','出演者'],['live','当日'],['results','実績']],this.tab));this.bind();this.bindFestival()}
 venue(){return VENUES.find(v=>v.id===this.state.plan.venue)}
 budget(){const p=this.state.plan,v=this.venue(),fees=ARTISTS.filter(a=>p.artists.includes(a.id)).reduce((x,a)=>x+a.fee,0);return Math.round(v.cost+fees+p.promotion+p.staff*9000+p.stages*80000+(p.sound+p.lighting+p.security+p.food+p.goods)*2800)}
 view(){const s=this.state,p=s.plan;if(this.tab==='artists')return`<div class="section-title"><h2>出演アーティスト</h2><span class="chip">${p.artists.length}組選択</span></div><div class="card-grid">${ARTISTS.map(a=>`<article class="item-card"><div class="row"><h4>${a.name}</h4><span class="chip">${a.genre}</span></div><p>出演料 ${money(a.fee)}</p>${meter('人気',a.popularity)}${meter('SNS影響',a.sns)}<button class="btn ${p.artists.includes(a.id)?'danger':'primary'}" data-artist="${a.id}">${p.artists.includes(a.id)?'出演を外す':'出演交渉'}</button></article>`).join('')}</div>`;
 if(this.tab==='live')return this.liveView();if(this.tab==='results')return this.resultView();return`<div class="section-title"><div><p class="eyebrow">EVENT PLAN</p><h2>${escapeHTML(p.name)}</h2></div><button class="btn primary" id="start-event" ${s.live?'disabled':''}>準備して開催 →</button></div><section class="panel"><div class="field"><label>イベント名</label><input id="event-name" value="${escapeHTML(p.name)}"></div><div class="field"><label>会場</label><select id="venue">${VENUES.map(v=>`<option value="${v.id}" ${v.id===p.venue?'selected':''}>${v.name}（${v.capacity.toLocaleString()}人）</option>`).join('')}</select></div><div class="control-row"><label>チケット価格</label><b class="control-value">${money(p.ticket)}</b><input data-plan="ticket" type="range" min="2000" max="18000" step="100" value="${p.ticket}"></div><div class="control-row"><label>宣伝費</label><b class="control-value">${money(p.promotion)}</b><input data-plan="promotion" type="range" min="0" max="1200000" step="10000" value="${p.promotion}"></div><div class="meter-pair">${['sound','lighting','security','food','goods'].map((k,i)=>`<div class="control-row"><label>${['音響','照明','警備','飲食','グッズ'][i]}</label><b class="control-value">${p[k]}</b><input data-plan="${k}" type="range" min="20" max="100" value="${p[k]}"></div>`).join('')}</div><div class="control-row"><label>スタッフ</label><b class="control-value">${p.staff}人</b><input data-plan="staff" type="range" min="10" max="300" value="${p.staff}"></div><div class="control-row"><label>ステージ</label><b class="control-value">${p.stages}</b><input data-plan="stages" type="range" min="1" max="4" value="${p.stages}"></div></section><section class="panel"><div class="row wrap"><b>概算費用 ${money(this.budget())}</b><span class="chip">手元 ${money(s.cash)}</span></div></section>`}
 liveView(){const l=this.state.live;if(!l)return`<section class="panel"><h2>開催予定はありません</h2><p class="muted">企画タブで会場や出演者を決めて開催してください。</p></section>`;return`<section class="live-stage"><div class="row"><span class="pulse"></span><b>LIVE ${l.minute}:00</b><div class="spacer"></div><span>${l.weather}</span></div><h2>${escapeHTML(this.state.plan.name)}</h2>${meter('進行',l.progress)}${meter('会場混雑',l.crowd)}<div class="resource-strip">${stat('来場者',l.attendance)}${stat('売上',l.sales,'money')}${stat('SNS投稿',l.posts)}${stat('満足度',l.satisfaction)}</div><button class="btn primary" id="live-toggle">${l.running?'一時停止':'進行する'}</button></section><div class="section-title"><h3>当日ログ</h3></div><section class="panel timeline">${l.logs.slice(-8).reverse().map(x=>`<div class="log"><time>${x.time}:00</time><span>${x.text}</span></div>`).join('')}</section>`}
 resultView(){const r=this.state.lastResult;if(!r)return`<section class="panel"><h2>実績はまだありません</h2><p class="muted">イベントを完走すると詳細な収支が表示されます。</p></section>`;return`<div class="section-title"><h2>イベント結果</h2><span class="chip">${r.weather}</span></div><div class="resource-strip">${stat('来場者',r.attendance)}${stat('満足度',r.satisfaction)}${stat('SNS評価',r.sns)}${stat('最終利益',r.profit,'money')}</div><section class="panel"><h3>収支</h3>${[['チケット売上',r.ticket],['飲食売上',r.food],['グッズ売上',r.goods],['出演料',-r.artistFees],['会場費',-r.venueCost],['人件費・運営費',-r.operations]].map(([k,v])=>`<div class="row" style="padding:9px 0;border-bottom:1px solid #ffffff0c"><span>${k}</span><b class="spacer" style="text-align:right;color:${v>=0?'var(--mint)':'var(--red)'}">${money(v)}</b></div>`).join('')}${chart(this.state.history)}</section>`}
 advice(){const p=this.state.plan,v=this.venue();if(!p.artists.length)return'出演者が決まっていません。集客力と出演料のバランスを考えましょう。';if(p.security<40||p.staff<v.capacity/100)return'警備またはスタッフが少なく、混雑時のトラブルが増えます。';if(this.budget()>this.state.cash)return'概算費用が会社資金を超えています。規模か品質を調整してください。';return'企画は開催可能です。屋外会場では天候リスクも予算に含めましょう。'}
 eventView(){const e=this.state.pendingEvent;return`<article class="item-card event-card"><h4>${e.title}</h4><p>${e.text}</p>${e.options?e.options.map((o,i)=>`<button class="btn" data-event="${i}">${o.label}</button>`).join(''):'<button class="btn" data-dismiss-event>確認</button>'}</article>`}
 bindFestival(){document.querySelectorAll('[data-plan]').forEach(x=>{x.oninput=()=>{const key=x.dataset.plan,value=+x.value;this.state.plan[key]=value;const out=x.parentElement.querySelector('.control-value');out.textContent=['ticket','promotion'].includes(key)?money(value):key==='staff'?`${value}人`:String(value);this.save(false)};x.onchange=()=>this.render()});document.querySelector('#event-name')?.addEventListener('change',e=>{this.state.plan.name=e.target.value.slice(0,30)||'WORLDIA BEAT';this.commit()});document.querySelector('#venue')?.addEventListener('change',e=>{this.state.plan.venue=e.target.value;this.commit()});document.querySelectorAll('[data-artist]').forEach(b=>b.onclick=()=>{const a=this.state.plan.artists,i=a.indexOf(b.dataset.artist);if(i>=0)a.splice(i,1);else if(a.length<8)a.push(b.dataset.artist);else toast('出演者は8組までです','bad');this.commit()});document.querySelector('#start-event')?.addEventListener('click',()=>this.startEvent());document.querySelector('#live-toggle')?.addEventListener('click',()=>this.toggleLive());document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{if(!resolveEvent(this.state,+b.dataset.event))return toast('この選択に必要な資金が足りません','bad');this.commit()});document.querySelector('[data-dismiss-event]')?.addEventListener('click',()=>{this.state.pendingEvent=null;this.commit()})}
 startEvent(){const s=this.state,p=s.plan,cost=this.budget();if(!p.artists.length)return toast('出演者を1組以上選んでください','bad');if(!this.spend(cost))return;const v=this.venue(),weather=v.outdoor?pick(['晴れ','晴れ','曇り','雨','大雨','猛暑']):'晴れ';s.live={progress:0,minute:10,attendance:0,target:0,sales:0,posts:0,satisfaction:50,crowd:0,weather,running:false,logs:[{time:10,text:'開場準備が完了しました'}],cost};this.tab='live';this.commit()}
 toggleLive(){const l=this.state.live;l.running=!l.running;clearInterval(this.liveTimer);if(l.running)this.liveTimer=setInterval(()=>this.tickLive(),700);this.render()}
 tickLive(){const s=this.state,l=s.live,p=s.plan,v=this.venue(),artists=ARTISTS.filter(a=>p.artists.includes(a.id)),artistDraw=artists.reduce((a,x)=>a+x.draw,0),weather=WEATHER[l.weather],priceEffect=clamp(1.45-p.ticket/(5500+s.companyRep*35),.35,1.15),promotion=1+p.promotion/900000,lure=(artistDraw*32+s.companyRep*38+s.followers*.12)*priceEffect*promotion*weather.attendance*this.difficulty().demand;l.target=Math.min(v.capacity,Math.round(lure));l.progress+=10;l.minute++;const arrival=l.progress<45?(l.target/5):rnd(0,l.target*.006);l.attendance=Math.min(l.target,Math.round(l.attendance+arrival));l.crowd=clamp(l.attendance/v.capacity*75+p.stages*4-p.staff/v.capacity*300);const quality=(p.sound+p.lighting)/2,ops=(p.security+p.staff/Math.max(1,v.capacity)*5000)/2;l.satisfaction=clamp(48+quality*.25+ops*.16+weather.satisfaction-l.crowd*.12);l.sales=Math.round(l.attendance*p.ticket+l.attendance*(p.food*8+p.goods*6));l.posts=Math.round(l.attendance*(artists.reduce((a,x)=>a+x.sns,0)/Math.max(1,artists.length))/110);if([20,50,80].includes(l.progress))l.logs.push({time:l.minute,text:pick(['メインステージが大きく盛り上がっています','飲食エリアに列ができています','SNSの投稿数が急上昇しています','ステージ転換は予定通りです'])});if(l.progress>=100)this.finishEvent();else this.render()}
 finishEvent(){clearInterval(this.liveTimer);const s=this.state,l=s.live,p=s.plan,v=this.venue(),artists=ARTISTS.filter(a=>p.artists.includes(a.id)),ticket=l.attendance*p.ticket,food=Math.round(l.attendance*p.food*8),goods=Math.round(l.attendance*p.goods*6),artistFees=artists.reduce((a,x)=>a+x.fee,0),operations=Math.round(p.promotion+p.staff*9000+p.stages*80000+(p.sound+p.lighting+p.security+p.food+p.goods)*2800),profit=ticket+food+goods-artistFees-v.cost-operations;s.cash+=ticket+food+goods;s.companyRep=clamp(s.companyRep+(l.satisfaction-55)*.12);s.followers+=l.posts;s.eventsHeld++;s.history=trend(s.history,Math.max(0,profit));s.lastResult={attendance:l.attendance,satisfaction:Math.round(l.satisfaction),sns:Math.round(clamp(35+l.posts/Math.max(1,l.attendance)*90)),profit,ticket,food,goods,artistFees,venueCost:v.cost,operations,weather:l.weather};s.live=null;s.turn++;rollEvent('festival',s,this.difficulty());floatDelta(`${profit>=0?'+':''}${money(profit)}`,profit<0);this.tab='results';this.commit()}
}
