import{GameBase}from'../../js/game-base.js';
import{app,stat,meter,tabs,chart,toast,floatDelta}from'../../js/ui.js';
import{clamp,rnd,pick,money,uid}from'../../js/config.js';
import{demand,trend,satisfaction}from'../../js/economy.js';
import{rollEvent,resolveEvent}from'../../js/events.js';
import{SHOP_TYPES,UPGRADES,NAMES}from'./data.js';
export function createShopState(difficulty,type='cafe'){
 const d=SHOP_TYPES[type];return{version:1,difficulty,turn:1,kind:type,name:`${d.name} WORLDIA店`,cash:Math.round(350000*({EASY:1.35,NORMAL:1,HARD:.72}[difficulty])),sales:0,profit:0,customers:0,reputation:52,popularity:45,cleanliness:88,followers:120,level:1,economy:50,capacity:34,quality:48,speed:45,inventory:0,products:d.products.map(([name,cost,price],i)=>({id:uid(),name,cost,price,popularity:62-i*8,stock:35})),staff:[],upgrades:{seats:0,kitchen:0,interior:0,ads:0,cleaner:0},history:[0],logs:['お店を開業しました。'],pendingEvent:null,tutorial:0};
}
export class ShopGame extends GameBase{
 constructor(home){super('shop',home)}
 render(){const s=this.state;const content=`<div class="resource-strip">${stat('所持金',s.cash,'money')}${stat('今日の売上',s.sales,'money')}${stat('利益',s.profit,'money')}${stat('客数',s.customers)}${stat('評判',s.reputation)}${stat('店舗Lv',s.level)}</div><div class="game-layout"><section>${this.view()}</section><aside class="panel"><h3>店舗コンディション</h3>${meter('人気',s.popularity)}${meter('清潔度',s.cleanliness)}${meter('品質',s.quality)}${meter('提供速度',s.speed)}<div class="notice">${this.advice()}</div>${s.pendingEvent?this.eventView():''}</aside></div>`;app().innerHTML=this.shell(content,tabs([['overview','概要'],['products','商品'],['staff','従業員'],['upgrades','拡張']],this.tab));this.bind();this.bindShop()}
 view(){const s=this.state;if(this.tab==='products')return`<div class="section-title"><h2>商品と在庫</h2><button class="btn" id="stock-all">一括仕入れ</button></div><div class="card-grid">${s.products.map(p=>`<article class="item-card"><h4>${p.name}</h4><p>原価 ${money(p.cost)}・在庫 ${p.stock}</p>${meter('商品人気',p.popularity)}<div class="control-row"><input type="range" min="${p.cost}" max="${p.cost*6}" step="10" value="${p.price}" data-price="${p.id}"><b class="control-value">${money(p.price)}</b></div><div class="actions"><button class="btn" data-stock="${p.id}">20個仕入 ${money(p.cost*20)}</button></div></article>`).join('')}</div>`;
 if(this.tab==='staff')return`<div class="section-title"><h2>従業員</h2><button class="btn primary" id="hire">採用する</button></div>${s.staff.length?`<div class="card-grid">${s.staff.map(x=>`<article class="item-card"><div class="row"><h4>${x.name}</h4><span class="chip">給料 ${money(x.salary)}</span></div>${meter('接客',x.service)}${meter('調理',x.cooking)}${meter('スピード',x.speed)}${meter('満足度',x.satisfaction)}<p>疲労 ${Math.round(x.fatigue)}</p><button class="btn danger" data-fire="${x.id}">退職手続き</button></article>`).join('')}</div>`:`<div class="panel"><p class="muted">まだ従業員はいません。客数が増える前に採用すると待ち時間を抑えられます。</p></div>`}`;
 if(this.tab==='upgrades')return`<div class="section-title"><h2>店舗拡張</h2><span class="muted">投資で強みを作る</span></div><div class="card-grid">${UPGRADES.map(u=>{const lv=s.upgrades[u.id],cost=Math.round(u.base*(1+lv*.8));return`<article class="item-card"><div class="row"><h4>${u.name}</h4><span class="chip">Lv ${lv}</span></div><p>${u.desc}</p><button class="btn primary" data-upgrade="${u.id}">${money(cost)}で強化</button></article>`}).join('')}</div>`;
 return`<div class="section-title"><div><p class="eyebrow">${SHOP_TYPES[s.kind].name}</p><h2>${s.name}</h2></div><button class="btn primary" id="next-day">営業開始 →</button></div><section class="panel"><h3>売上推移</h3>${chart(s.history)}<div class="meter-pair">${meter('SNSフォロワー',Math.min(100,s.followers/50))}${meter('地域景気',s.economy)}</div></section><div class="section-title"><h3>最近の動き</h3></div><div class="panel timeline">${s.logs.slice(-6).reverse().map((l,i)=>`<div class="log"><time>${s.turn-i}日</time><span>${l}</span></div>`).join('')}</div>`}
 advice(){const s=this.state;if(s.products.some(p=>p.stock<8))return'在庫が少ない商品があります。品切れは客数と評判を下げます。';if(s.customers>s.capacity*.9)return'店内が混雑しています。座席か人員へ投資すると機会損失を減らせます。';if(s.cleanliness<55)return'清潔度が低下しています。清掃を行うか設備を強化しましょう。';return'価格、在庫、人員のバランスは良好です。次の成長投資を検討できます。'}
 eventView(){const e=this.state.pendingEvent;return`<article class="item-card event-card"><h4>${e.title}</h4><p>${e.text}</p>${e.options?`<div class="event-options">${e.options.map((o,i)=>`<button class="btn" data-event="${i}">${o.label}</button>`).join('')}</div>`:'<button class="btn" data-dismiss-event>確認</button>'}</article>`}
 bindShop(){document.querySelector('#next-day')?.addEventListener('click',()=>this.nextDay());document.querySelectorAll('[data-price]').forEach(x=>x.oninput=()=>{const p=this.state.products.find(p=>p.id===x.dataset.price);p.price=+x.value;x.nextElementSibling.textContent=money(p.price);this.save(false)});document.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>this.stock(b.dataset.stock));document.querySelector('#stock-all')?.addEventListener('click',()=>{const cost=this.state.products.reduce((a,p)=>a+p.cost*20,0);if(this.spend(cost)){this.state.products.forEach(p=>p.stock+=20);this.commit()}});document.querySelector('#hire')?.addEventListener('click',()=>this.hire());document.querySelectorAll('[data-fire]').forEach(b=>b.onclick=()=>{this.state.staff=this.state.staff.filter(x=>x.id!==b.dataset.fire);this.commit()});document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>this.upgrade(b.dataset.upgrade));document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{resolveEvent(this.state,+b.dataset.event);this.commit()});document.querySelector('[data-dismiss-event]')?.addEventListener('click',()=>{this.state.pendingEvent=null;this.commit()})}
 stock(id){const p=this.state.products.find(x=>x.id===id),cost=p.cost*20;if(this.spend(cost)){p.stock+=20;toast(`${p.name}を仕入れました`);this.commit()}}
 hire(){const skill=()=>Math.round(rnd(35,78));this.state.staff.push({id:uid(),name:pick(NAMES),salary:Math.round(rnd(7800,12800)),service:skill(),cooking:skill(),speed:skill(),fatigue:0,satisfaction:70});this.commit()}
 upgrade(id){const u=UPGRADES.find(x=>x.id===id),lv=this.state.upgrades[id],cost=Math.round(u.base*(1+lv*.8));if(!this.spend(cost))return;this.state.upgrades[id]++;if(id==='seats')this.state.capacity+=12;if(id==='kitchen'){this.state.quality=clamp(this.state.quality+7);this.state.speed=clamp(this.state.speed+8)}if(id==='interior'){this.state.reputation=clamp(this.state.reputation+8);this.state.popularity=clamp(this.state.popularity+5)}if(id==='ads'){this.state.popularity=clamp(this.state.popularity+9);this.state.followers+=250}if(id==='cleaner')this.state.cleanliness=clamp(this.state.cleanliness+12);this.state.level=1+Object.values(this.state.upgrades).reduce((a,b)=>a+b,0);floatDelta(`店舗Lv ${this.state.level}`);this.commit()}
 nextDay(){const s=this.state,d=this.difficulty(),staffPower=s.staff.reduce((a,x)=>a+x.speed*.14+x.service*.08,0),capacity=s.capacity+staffPower,avgPrice=s.products.reduce((a,p)=>a+p.price,0)/s.products.length,avgFair=s.products.reduce((a,p)=>a+p.cost*3,0)/s.products.length,priceRatio=avgPrice/avgFair,available=s.products.filter(p=>p.stock>0),stockFactor=available.length/s.products.length,base=SHOP_TYPES[s.kind].base*d.demand;let wanted=demand(base,s.popularity,priceRatio,s.quality,s.economy)*stockFactor;const served=Math.round(Math.min(wanted,capacity));let sales=0,cost=0;for(let i=0;i<served;i++){const p=pick(available);if(!p||p.stock<=0)continue;p.stock--;sales+=p.price;cost+=p.cost}const wages=s.staff.reduce((a,x)=>a+x.salary,0),fixed=(8000+s.level*1800)*d.cost*(s.costShock?1.2:1),profit=Math.round(sales-cost-wages-fixed);s.cash+=profit;s.sales=Math.round(sales);s.profit=profit;s.customers=served;s.cleanliness=clamp(s.cleanliness-served*(.1-s.upgrades.cleaner*.012)+3);const sat=satisfaction(s.quality,clamp(120-priceRatio*50),clamp(100-wanted/Math.max(capacity,1)*45),Math.max(0,60-s.cleanliness)*.25);s.reputation=clamp(s.reputation+(sat-55)*.035);s.popularity=clamp(s.popularity+(s.reputation-50)*.025+s.upgrades.ads*.18-d.decay*.12);s.followers=Math.max(0,Math.round(s.followers+served*(s.reputation/100)*.3));s.staff.forEach(x=>{x.fatigue=clamp(x.fatigue+served/Math.max(1,s.staff.length)*.35-8);x.satisfaction=clamp(x.satisfaction+(profit>0?1:-2)-x.fatigue*.015)});s.economy=clamp(s.economy+rnd(-2.4,2.4));s.history=trend(s.history,s.sales);s.turn++;s.costShock=Math.max(0,(s.costShock||0)-1);s.weatherShock=Math.max(0,(s.weatherShock||0)-1);rollEvent('shop',s,d);s.logs.push(`${served}人が来店、${profit>=0?'利益':'損失'} ${money(Math.abs(profit))}`);floatDelta(`${profit>=0?'+':''}${money(profit)}`,profit<0);this.commit()}
}
